server:
  port: 80

spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
  datasource: #数据源连接参数
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC
      username: root
      password: root

pagehelper: #mybatis分页助手
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: false

mybatis-plus:
  configuration:
    #    map-underscore-to-camel-case: false #关闭自动驼峰映射
    cache-enabled: false #关闭缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印MP日志,上线时关闭该配置
  global-config:
    db-config:
      id-type: auto #全局默认主键类型